/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rocha82;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ApiTest {
    App app=new App();
    @Test void testGetMessage() {
        assertEquals("H","H");
    }
}
