/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rocha82.daos;

import com.rocha82.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
