#URL: "jdbc:sqlite:teste.db"
spring.datasource.url=jdbc:sqlite:/data/data/com.termux/files/home/java/portfolio/daos/src/main/resources/teste.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# O SQLite não tem usuário/senha por padrão
spring.datasource.username=sa
spring.datasource.password=

# Configurações JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Ajuste o dialeto para usar o caminho do pacote comunitário oficial:
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
# Define o formato global para LocalDate (apenas data simples)
spring.jackson.date-format=yyyy-MM-dd

# Força o Spring a respeitar o fuso horário local e não converter tudo para GMT/UTC
spring.jackson.time-zone=America/Sao_Paulo

# Desativa a conversão de datas para timestamps numéricos (garante que virem Strings legíveis)
spring.jackson.options.WRITE_DATES_AS_TIMESTAMPS=false