/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    
alias(libs.plugins.spring.boot)
   application
}
dependencies {
    implementation (libs.spring.boot.web)
    testImplementation(libs.junit.jupiter)
  testRuntimeOnly(libs.junit.platform)
//    implementation("org.apache.commons:commons-text")
    implementation(project(":DTOs"))
}
tasks.test{useJUnitPlatform()}
application {
    // Define the main class for the application.
    mainClass = "com.rocha82.App"
    
}

   