/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
alias(libs.plugins.spring.boot)
id("org.example.greeting")
   // id("buildlogic.java-application-conventions")
   application
}
dependencies {
    implementation (libs.spring.boot.web)
    testImplementation(libs.junit.jupiter)
  testRuntimeOnly(libs.junit.platform)
//    implementation("org.apache.commons:commons-text")
    implementation(project(":repositories"))
}
tasks.test{useJUnitPlatform()}
application {
    // Define the main class for the application.
    mainClass = "com.rocha82.App"
}
